/* Generated by CMake from config.h.in
 *
 * Project-wide configuration header. This file is included by all C and C++
 * source files in the project. The first part contains macro definitions that
 * are used globally across the project.
 * 
 * options.h is included here for predefines common to C and LPC code.
 * 
 * Note that func_spec.c also includes config.h to get the option macros, with
 * _LPC_FUNC_SPEC defined to opt-out C/C++-specific definitions.
 */

/* #undef HAVE_ARGP_H */
/* #undef HAVE_DIRENT_H */
#define HAVE_FCNTL_H
#define HAVE_INTTYPES_H
#define HAVE_LIMITS_H
/* #undef HAVE_NETDB_H */
#define HAVE_SIGNAL_H
#define HAVE_STDARG_H
#define HAVE_STDBOOL_H
#define HAVE_STDDEF_H
#define HAVE_STDINT_H
/* #undef HAVE_SYS_IOCTL_H */
/* #undef HAVE_SYS_PARAM_H */
/* #undef HAVE_SYS_RESOURCE_H */
/* #undef HAVE_SYS_TIME_H */
#define HAVE_SYS_TYPES_H
/* #undef HAVE_SYS_WAIT_H */
/* #undef HAVE_TERMIOS_H */
/* #undef HAVE_UNISTD_H */
/* #undef HAVE_ARPA_TELNET_H */

/* #undef HAVE_GETTIMEOFDAY */
/* #undef HAVE_POLL */
/* #undef HAVE_REALPATH */
/* #undef HAVE_STPCPY */
#define HAVE_STRTOD

/* #undef HAVE_BOOST */
/* #undef HAVE_BOOST_JSON */
/* #undef BOOST_JSON_HEADER_ONLY */
#define HAVE_JSONCPP
/* #undef HAVE_OPENSSL */
/* #undef HAVE_CURL */
/* #undef HAVE_CARES */

/* #undef HAVE_GTEST */

/* MudOS options */
#include "options.h"

#ifndef _LPC_FUNC_SPEC

#define PACKAGE "neolith"
#define VERSION "1.0.0"

#ifndef RETSIGTYPE
/* C99 standard */
#define RETSIGTYPE void
#endif

/* Mark non-returning functions (fatal paths, longjmp, or C++ exception throw). */
#if defined(__GNUC__) || defined(__clang__)
#  define NO_RETURN __attribute__((noreturn))
#else
#  define NO_RETURN
#endif

#ifdef _WIN32
#  define PLATFORM_UTF8_LOCALE ".UTF-8"
#else
#  define PLATFORM_UTF8_LOCALE "C.UTF-8"
#endif

#ifndef _WIN32
typedef unsigned char BYTE;
#endif

#endif /* _LPC_FUNC_SPEC */
