import assert from 'node:assert/strict';
import {PlayerStateObserver} from '../web/player_state.js';
const o=new PlayerStateObserver();
o.begin('hp');
o.consume('形體 90/100\t精 80/90\t氣 70/80\t神 60/70\n食物 50/100\t飲水 40/100\t疲勞 30/100\n');
assert.deepEqual(o.state.vitals.hp,{current:90,limit:100,limitKind:'effective'});
assert.deepEqual(o.state.vitals.food,{current:50,limit:100,limitKind:'maximum'});
o.begin('skills');
o.consume('  基本內功 (force)                                     - 爐火純青   150\n  基本劍術 - 神劍術 (divine-sword)                         - 登峰造極   145 (-5)\n');
assert.equal(o.state.skills[0].skillId,'force');
assert.equal(o.state.skills[0].effectiveLevel,150);
assert.equal(o.state.skills[1].mappedId,'divine-sword');
assert.equal(o.state.skills[1].rawLevel,150);
o.begin('inventory');
o.consume('你身上帶著下列這些東西(負重 37%)﹕\nˇ長劍◎\n  一顆石頭\n');
assert.equal(o.state.inventoryMeta.encumbrancePercent,37);
assert.deepEqual(o.state.inventory[0],{text:'長劍',equipped:true,kept:true,raw:'ˇ長劍◎'});
assert.equal(o.state.inventory[1].equipped,false);
console.log('v1.6 canonical player-state tests passed');
