const $=s=>document.querySelector(s);let rows=[];
async function status(){const s=await fetch('/api/status').then(r=>r.json());$('#status').textContent=JSON.stringify(s,null,2)}
function label(x){return `${x.short||x.name||x.ids?.[0]||x.file} · ${x.type||''}`}
function render(){const q=$('#search').value.trim().toLowerCase();const filt=rows.filter(x=>(!$('#manualOnly').checked||(x.manual_review||[]).length)&&(!q||JSON.stringify([x.file,x.short,x.name,x.ids,x.functions,x.skills,x.skill_maps]).toLowerCase().includes(q)));$('#count').textContent=`${filt.length} / ${rows.length}`;$('#entries').innerHTML='';filt.slice(0,3000).forEach(x=>{const b=document.createElement('button');b.className='roomitem';b.textContent=label(x);b.onclick=()=>openSource(x);$('#entries').appendChild(b)})}
async function loadCatalog(){const f=$('#catalog').value,r=await fetch('/api/catalog?file='+encodeURIComponent(f));if(!r.ok){rows=[];render();$('#entries').insertAdjacentHTML('afterbegin','<p class="err">尚未建立完整 upstream 索引。</p>');return}const data=await r.json();rows=Array.isArray(data)?data:[];render()}
async function openSource(x){const p='mudlib/'+x.file;$('#path').value=p;$('#meta').textContent=JSON.stringify(x,null,2);const r=await fetch('/api/source?path='+encodeURIComponent(p));$('#source').value=await r.text()}
$('#save').onclick=async()=>{const p=$('#path').value;if(!p)return;const r=await fetch('/api/source?path='+encodeURIComponent(p),{method:'PUT',body:$('#source').value});if(r.ok){const x=await r.json();$('#msg').textContent='已儲存 · '+x.backup}else $('#msg').textContent='失敗：'+await r.text()}
$('#loadCatalog').onclick=loadCatalog;$('#catalog').onchange=loadCatalog;$('#search').oninput=render;$('#manualOnly').onchange=render;async function openInitialPath(){const p=new URLSearchParams(location.search).get('path');if(!p)return;const r=await fetch('/api/entity?path='+encodeURIComponent(p));if(r.ok)openSource(await r.json())}
status();loadCatalog().then(openInitialPath);
